baseURL = "https://anacantarini.github.io/meu-site/"
locale = "pt-br"
title = "Meu Site"

theme = ["github.com/zerostaticthemes/hugo-winston-theme"]

[params]
  description = "Meu site pessoal com Hugo Winston"
